version: 1
build:
  main: x/../
  proto:
    path: proto
    third_party_paths:
    - third_party/proto
    - proto_vendor
accounts:
- name: alice
  coins:
  - 200000000ustay
  - 200000000stake
  - 25000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
- name: bob
  coins:
  - 100000000ustay
  - 100000000stake
  - 5000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2
faucet:
  name: bob
  coins:
  - 500000ustay
  - 100000stake
  host: 0.0.0.0:4500
client:
  vuex:
    path: vue/src/store
  openapi:
    path: docs/static/openapi.yml
validators:
- name: alice
  bonded: 100000000stake
