build:
  main: x/../
accounts:
  - name: alice
    coins:
      [
        "200000000ustay",
        "200000000stake",
        "25000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
      ]
  - name: bob
    coins:
      [
        "100000000ustay",
        "100000000stake",
        "5000ibc/27394FB092D2ECCD56123C74F36E4C1F926001CEADA9CA97EA622B25F41E5EB2",
      ]
validator:
  name: alice
  staked: "100000000stake"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: bob
  coins: ["500000ustay", "100000stake"]
