version: "3"

services:

  stayking:
    image: soohoio:localstayking
    build:
      context: ../../../
      args:
        RUNNER_IMAGE: alpine:3.16
        GO_VERSION: 1.19
    volumes:
      - ./scripts/start.sh:/home/stayking/start.sh
      - ./scripts/testnetify.py:/home/stayking/testnetify.py
      - ./state_export.json:/home/stayking/state_export.json
      - $HOME/.stayking/:/home/stayking/.stayking/
    entrypoint:
      - /home/stayking/start.sh
    environment:
      - MONIKER=val
      - CHAIN_ID=localstayking
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
