version: "3"
services:
  stayking1:
    image: soohoio:stayking
    hostname: stayking1
    volumes:
      - ./state/stayking1:/home/stayking/.stayking
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  gaia1:
    image: soohoio:gaia
    hostname: gaia1
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  relayer-gaia:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-gaia" ]