version: "3"
services:
  stayking1:
    image: soohoio:stayking
    volumes:
      - ./state/stayking1:/home/stayking/.stayking
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  stayking2:
    image: soohoio:stayking
    volumes:
      - ./state/stayking2:/home/stayking/.stayking

  stayking3:
    image: soohoio:stayking
    volumes:
      - ./state/stayking3:/home/stayking/.stayking

  gaia1:
    image: soohoio:gaia
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"

  gaia2:
    image: soohoio:gaia
    volumes:
      - ./state/gaia2:/home/gaia/.gaia

  gaia3:
    image: soohoio:gaia
    volumes:
      - ./state/gaia3:/home/gaia/.gaia

  gaia4:
    image: soohoio:gaia
    volumes:
      - ./state/gaia4:/home/gaia/.gaia

  gaia5:
    image: soohoio:gaia
    volumes:
      - ./state/gaia5:/home/gaia/.gaia

  hermes:
    image: soohoio:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ./state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer-gaia:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-gaia" ]