version: "3"
services:
  stayking1:
    image: soohoio:stayking
    hostname: stayking1
    volumes:
      - ./state/stayking1:/home/stayking/.stayking
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  stayking2:
    image: soohoio:stayking
    hostname: stayking2
    volumes:
      - ./state/stayking2:/home/stayking/.stayking

  stayking3:
    image: soohoio:stayking
    hostname: stayking3
    volumes:
      - ./state/stayking3:/home/stayking/.stayking

  gaia1:
    image: soohoio:gaia
    hostname: gaia1
    volumes:
      - ./state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  osmosis1:
    image: soohoio:osmosis
    hostname: osmosis1
    volumes:
      - ./state/osmosis1:/home/osmosis/.osmosisd
    ports:
      - "26457:26657"
      - "1297:1317"
      - "9070:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  relayer-gaia:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-gaia:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-gaia" ]
  relayer-osmosis:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-osmosis:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-osmosis" ]

  hermes-gaia:
    image: soohoio:hermes
    volumes:
      - ./state/hermes-gaia:/home/hermes/.hermes
    restart: always
