global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  stayking:
    type: cosmos
    value:
      key: rly1
      chain-id: stayking-hub
      rpc-addr: http://stayking1:26657
      account-prefix: sooho
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01ustay
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
  evmosMainnet:
    type: cosmos
    value:
      key: rly3
      chain-id: evmos_9001-2
      rpc-addr: https://tendermint.bd.evmos.org:26657
      account-prefix: evmos
      keyring-backend: test
      gas-adjustment: 1.5
      gas-prices: 100000000000aevmos
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
      extra-codecs:
        - ethermint
paths:
  stayking-evmosMainnet:
    src:
        chain-id: stayking-hub
        client-id: 07-tendermint-4
        connection-id: connection-1
    dst:
        chain-id: evmos_9001-2
        client-id: 07-tendermint-109
        connection-id: connection-64
    src-channel-filter:
        rule: ""
        channel-list: []
