---
name: Feature Request
about: Suggest an idea for this project
title: ''
labels: ''
assignees: ''

---

  <!-- < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < < ☺
  v                            ✰  Thanks for opening an issue! ✰
  v    Before smashing the submit button please review the template.
v    Word of caution: poorly thought-out proposals may be rejected
  v                     without deliberation
  ☺ > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > > >  -->
  
  ## Summary
  
  Short, concise description of the proposed feature.
  
  ## Problem Definition
  
  A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
  
  Why do we need this feature?
  
  What problems may be addressed by introducing this feature?
  
  What benefits does the chain stand to gain by including this feature?
  
  Are there any disadvantages of including this feature?
  
  ## Proposal
  
  A clear and concise description of the solution you'd like (what you want to happen).
  
  ## Alternatives
  
  A clear and concise description of any alternative solutions or features you've considered.
  
  ## Additional context
  
  Add any other context or screenshots about the feature request here.
  
  ____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged