version: "3"

services:
  staykingd:
    image: soohoio:localstayking
    build:
      context: ../../../
      args:
        RUNNER_IMAGE: alpine:3.15
        GO_VERSION: 1.19
    volumes:
      - ./scripts/start.sh:/home/stayking/start.sh
      - $HOME/.stayking/:/home/stayking/.stayking/
    entrypoint:
      - /home/stayking/start.sh
    ports:
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
