version: "3"
services:
  stayking1:
    image: soohoio:stayking
    volumes:
      - ./state/stayking1:/home/stayking/.stayking
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

  stayking2:
    image: soohoio:stayking
    hostname: stayking2
    volumes:
      - ./state/stayking2:/home/stayking/.stayking

  stayking3:
    image: soohoio:stayking
    hostname: stayking3
    volumes:
      - ./state/stayking3:/home/stayking/.stayking

  relayer-gaiaTestnet:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-gaiaTestnet:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-gaiaTestnet" ]
  relayer-evmosTestnet:
    image: soohoio:relayer
    volumes:
      - ./state/relayer-evmosTestnet:/home/relayer/.relayer
    restart: always
    command: [ "bash", "start.sh", "stayking-evmosTestnet" ]
  hermes-gaiaTestnet:
    image: soohoio:hermes
    volumes:
      - ./state/hermes-gaiaTestnet:/home/hermes/.hermes
    restart: always
