[mode]
[mode.clients]
enabled = true
refresh = true
misbehaviour = true

[mode.connections]
enabled = true

[mode.channels]
enabled = true

[mode.packets]
enabled = true
clear_interval = 100
clear_on_start = true

[rest]
enabled = true
host = '0.0.0.0'
port = 3000

[telemetry]
enabled = true
host = '0.0.0.0'
port = 3001

[[chains]]
id = 'stayking-testnet-001'
rpc_addr = 'http://stayking1:26657'
grpc_addr = 'http://stayking1:9090'
websocket_addr = 'ws://stayking1:26657/websocket'
rpc_timeout = '10s'
account_prefix = 'sooho'
key_name = 'rly1'
store_prefix = 'ibc'
default_gas = 8000000
max_gas = 9000000
gas_price = { price = 0.01, denom = 'ustay' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 200000
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '36h'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
sequential_batch_tx = false

[[chains]]
id = 'theta-testnet-001'
rpc_addr = 'https://cosmos-testnet-archive.allthatnode.com:26657/AowVlngs1uvTAB6cbCEF2y3Xwy0Qk7qL'
grpc_addr = 'https://cosmos-testnet-archive.allthatnode.com:9090/AowVlngs1uvTAB6cbCEF2y3Xwy0Qk7qL'
websocket_addr = 'ws://cosmos-testnet-archive.allthatnode.com:26657/AowVlngs1uvTAB6cbCEF2y3Xwy0Qk7qL/websocket'
rpc_timeout = '10s'
account_prefix = 'cosmos'
key_name = 'rly2'
store_prefix = 'ibc'
default_gas = 8000000
max_gas = 9000000
gas_price = { price = 0.01, denom = 'uatom' }
gas_multiplier = 1.1
max_msg_num = 30
max_tx_size = 200000
clock_drift = '5s'
max_block_time = '10s'
trusting_period = '36h'
trust_threshold = { numerator = '1', denominator = '3' }
address_type = { derivation = 'cosmos' }
sequential_batch_tx = false
[chains.packet_filter]
policy = 'allow'
list = [
  ['ica*', '*'],
  ['transfer', 'channel-*'],
]