global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  stayking:
    type: cosmos
    value:
      key: rly1
      chain-id: stayking-testnet-001
      rpc-addr: http://stayking1:26657
      account-prefix: sooho
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01ustay
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
  evmosTestnet:
    type: cosmos
    value:
      key: rly3
      chain-id: evmos_9000-4
      rpc-addr: https://tendermint.bd.evmos.dev:26657/
      account-prefix: evmos
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 20000000000atevmos
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
      extra-codecs:
        - ethermint
paths:
  stayking-evmosTestnet:
    src:
      chain-id: stayking-testnet-001
    dst:
      chain-id: evmos_9000-4
    src-channel-filter:
      rule: ""
      channel-list: [ ]
