global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  stayking:
    type: cosmos
    value:
      key: rly1
      chain-id: stayking-localnet
      rpc-addr: http://stayking1:26657
      account-prefix: sooho
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01ustay
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  gaia:
    type: cosmos
    value:
      key: rly2
      chain-id: gaia-localnet
      rpc-addr: http://gaia1:26657
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01uatom
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct

paths:
  stayking-gaia:
    src:
      chain-id: stayking-localnet
    dst:
      chain-id: gaia-localnet
    src-channel-filter:
      rule: ""
      channel-list: []