global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  stayking:
    type: cosmos
    value:
      key: rly1
      chain-id: stayking-localnet
      rpc-addr: http://stayking1:26657
      account-prefix: sooho
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01ustay
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
  gaia:
    type: cosmos
    value:
      key: rly2
      chain-id: gaia-localnet
      rpc-addr: http://gaia1:26657
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01uatom
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
  osmosis:
    type: cosmos
    value:
      key: rly3
      chain-id: osmosis-localnet
      rpc-addr: http://osmosis1:26657
      account-prefix: osmo
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 0.01uosmo
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
  evmos:
    type: cosmos
    value:
      key: rly4
      chain-id: evmos_9001-2
      rpc-addr: http://evmos1:26657
      account-prefix: evmos
      keyring-backend: test
      gas-adjustment: 1.2
      gas-prices: 25000000000aevmos
      debug: true
      timeout: 60s
      output-format: json
      sign-mode: direct
      extra-codecs:
        - ethermint

paths:
  stayking-gaia:
    src:
      chain-id: stayking-localnet
    dst:
      chain-id: gaia-localnet
    src-channel-filter:
      rule: ""
      channel-list: []
  stayking-osmosis:
    src:
      chain-id: stayking-localnet
    dst:
      chain-id: osmosis-localnet
    src-channel-filter:
      rule: ""
      channel-list: [ ]
  stayking-evmos:
    src:
      chain-id: stayking-localnet
    dst:
      chain-id: evmos_9001-2
    src-channel-filter:
      rule: ""
      channel-list: [ ]